{
  "hash": "c8aa794917e2c375ae0159db0b57874c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Networks Data\"\n---\n\n\n\n## 3.1 Overview\n\nSocial network analysis (SNA) is the process of investigating social structures through the use of networks and graph theory. It is a technique used to map and measure relationships and flows between people, groups, organizations, computers, or other information/knowledge processing entities. SNA can be a useful tool for understanding the team structures, for example, in an online classroom. It can be an additional layer of understanding the outcomes (or predictors) of certain instructional interventions. Used this way SNA can be used to identify patterns and trends in social networks, as well as to understand how these networks operate. Additionally, SNA can be used to predict future behavior in social networks, and to design interventions that aim to improve the functioning of these networks.\n\n## 3.2 Accessing SNA Data\n\nSocial Network Analysis (SNA) relies on relational data—information about **connections** (edges) between entities (nodes) such as students, teachers, or organizations. Compared to traditional survey or tabular data, SNA requires **pairwise relational information**. In education, this could include “who collaborates with whom,” “who talks to whom,” or digital traces of discussion and collaboration in online platforms.\n\n### 3.2.1 Types and Sources of SNA Data\n\nThere are several common sources and structures for SNA data in educational and social science contexts:\n\n-   **Survey-based Network Data**: Collected via roster or name generator questions, e.g., “List the classmates you discuss assignments with.”\n-   **Behavioral/Observational Data**: Derived from logs of actual interactions, e.g., forum replies, emails, classroom seating.\n-   **Archival or Digital Trace Data**: Extracted from digital platforms such as MOOCs, LMS discussion forums, Slack, Twitter, or Facebook.\n-   **Administrative/Organizational Data**: Information about formal structures such as team membership or co-authorship.\n\n**Data Structure**: Most SNA data are formatted as: - **Edge List** (two columns: source and target) - **Adjacency Matrix** (rows and columns are actors; cell values indicate a tie) - **Node Attributes** (supplementary information about each node, e.g., gender, role)\n\n### 3.2.2 Example 1: Creating a Simple Network from an Edge List\n\nBelow is an example of constructing a network from a simple CSV edge list. This mirrors typical classroom survey data (“who do you consider your friend in this class?”).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install and load the igraph package\n# install.packages(\"igraph\")\nlibrary(igraph)\n\n# Example: Load an edge list from CSV\nedge_list <- read.csv(\"data/friendship_edges.csv\")\n\n# Create the graph object (directed network)\ng <- graph_from_data_frame(edge_list, directed = TRUE)\n\n# Plot the network\nplot(g, main = \"Friendship Network\")\n```\n:::\n\n\n### 3.2.3 Example 2: Generating Network Data from Digital Traces\n\nMany educational datasets now come from online discussion forums, MOOCs, or LMS systems. For example, the MOOC case study (Kellogg & Edelmann, 2015) uses reply relationships in online courses to construct discussion networks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Suppose you have a data frame with columns: from_user, to_user\nmooc_edges <- read.csv(\"data/mooc_discussion_edges.csv\")\ng_mooc <- graph_from_data_frame(mooc_edges, directed = TRUE)\nplot(g_mooc, main = \"MOOC Discussion Network\")\n```\n:::\n\n\n### 3.2.4 Example 3: Collecting SNA Data via Surveys\n\nIf you want to collect your own network data:\n\n-   Ask participants to **name or select** (from a roster) their friends, collaborators, or contacts.\n\n-   Compile responses into an edge list.\n\n-   Example survey prompt:\n\n    > \"Please list up to five classmates you seek help from most frequently.\"\n\n::: callout-tip\n## Tip\n\nSurvey-based SNA is easier to manage with small to medium groups. For larger networks, digital trace or archival data may be more practical.\n:::\n\n### 3.2.5 Node Attribute Data\n\nYou can also load additional data about each node (student, teacher, etc.) to enable richer analyses (e.g., centrality by gender or role).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnode_attributes <- read.csv(\"data/friendship_nodes.csv\")\n# Add attributes to igraph object\nV(g)$gender <- node_attributes$gender[match(V(g)$name, node_attributes$name)]\n```\n:::\n\n\n### 3.2.6 Further Examples\n\n-   **Public Datasets**:\n    -   [MOOC Discussion Networks](https://github.com/kelloggm/ed-mooc-network)\n    -   [Add Health](https://www.cpc.unc.edu/projects/addhealth/documentation/network/)\n    -   [Common Core Twitter Networks (Supovitz et al.)](http://hashtagcommoncore.com/)\n-   **Synthetic Data**:\n    -   R's `igraph` package can also generate sample networks for practice:\n\n\n        ::: {.cell}\n        \n        ```{.r .cell-code}\n        library(igraph)\n        g_sample <- sample_gnp(n = 10, p = 0.3)\n        plot(g_sample, main = \"Random Sample Network\")\n        ```\n        \n        ::: {.cell-output-display}\n        ![](chapter-3_files/figure-html/sample-network-1.png){width=672}\n        :::\n        :::\n\n\n### 3.2.7 Best Practices and Tips\n\n::: callout-important\n## SNA Best Practices\n\n-   **Ethics**: Social network data can be sensitive. Protect anonymity and comply with IRB/data use guidelines.\n-   **Format Consistency**: Always clarify whether ties are directed/undirected, binary/weighted, and ensure consistent formatting.\n-   **Missing Data**: Especially in survey-based SNA, missing responses can impact network structure and interpretation.\n:::\n\n### 3.2.8 Summary\n\nAccessing SNA data involves both careful **design** (in the case of surveys/observations) and **extraction/wrangling** (in the case of digital traces or archival records). The choice of data source and structure will directly influence the kinds of questions you can answer with SNA.\n\n::: callout-note\n## Recommended Reading\n\n-   Borgatti, S. P., Everett, M. G., & Johnson, J. C. (2018). *Analyzing Social Networks* (2nd ed). SAGE.\n-   Kellogg, S., & Edelmann, A. (2015). Massive open online course discussion forums as networks.\n:::\n\n## 3.3 Network Management & Measurement in Social Network Analysis\n\n### 3.3.1 Purpose + Case\n\n**Purpose:** This section demonstrates how to manage, measure, and visualize large-scale discussion networks from online professional development settings. Through this real-world example, we guide readers in loading relational data, constructing a directed network, and conducting a suite of essential SNA measures. The focus is on classroom- and course-level online discussions, which are representative of many contemporary educational and research settings.\n\n**Case Study:** The case data comes from two cohorts of an online professional development program (“DLT1” and “DLT2”). Each cohort's discussion data includes (a) **edge list** data capturing who replied to whom, and (b) **node/actor** attributes describing roles (e.g., facilitator, expert). These data allow us to reconstruct and analyze the full structure of communication in two authentic online learning communities.\n\n### 3.3.2 Sample Research Questions\n\n-   **RQ1:** What is the overall structure of interaction in each online discussion cohort? Are they densely connected, or fragmented?\n-   **RQ2:** Who are the most central or influential actors in the network? How do facilitators or experts compare with regular participants?\n-   **RQ3:** To what extent are ties reciprocated (mutual) and how cohesive are the networks?\n-   **RQ4:** How do the network properties (e.g., density, reciprocity, clustering) compare between cohorts?\n\n### 3.3.3 Analysis\n\n#### Step 1: Install and Load Required Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install and load necessary libraries\n# install.packages(c(\"tidygraph\", \"ggraph\", \"readr\", \"janitor\"))\nlibrary(tidygraph)\nlibrary(ggraph)\nlibrary(readr)\nlibrary(janitor)\nlibrary(igraph)\nlibrary(dplyr)\n```\n:::\n\n\n#### Step 2: Import and Clean Data\n\nLoad Edges and Node Attributes for DLT1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load edge list (who replied to whom)\ndlt1_ties <- read_csv(\"data/dlt1-edges.csv\", \n  col_types = cols(Sender = col_character(), \n                   Receiver = col_character(), \n                   `Category Text` = col_skip(), \n                   `Comment ID` = col_character(), \n                   `Discussion ID` = col_character())) |> \n  clean_names()\n\n# Load node attributes (participant roles, etc.)\ndlt1_actors <- read_csv(\"data/dlt1-nodes.csv\", \n  col_types = cols(UID = col_character(), \n                   Facilitator = col_character(), \n                   expert = col_character(), \n                   connect = col_character())) |> \n  clean_names()\n\nhead(dlt1_ties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  sender receiver timestamp discussion_title discussion_category parent_category\n  <chr>  <chr>    <chr>     <chr>            <chr>               <chr>          \n1 360    444      4/4/13 1… Most important … Group N             Units 1-3 Disc…\n2 356    444      4/4/13 1… Most important … Group D-L           Units 1-3 Disc…\n3 356    444      4/4/13 1… DLT Resources—C… Group D-L           Units 1-3 Disc…\n4 344    444      4/4/13 1… Most important … Group O-T           Units 1-3 Disc…\n5 392    444      4/4/13 1… Most important … Group U-Z           Units 1-3 Disc…\n6 219    444      4/4/13 1… Most important … Group M             Units 1-3 Disc…\n# ℹ 3 more variables: discussion_identifier <chr>, comment_id <chr>,\n#   discussion_id <chr>\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dlt1_actors)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 13\n  uid   facilitator role1  experience experience2 grades location region country\n  <chr> <chr>       <chr>       <dbl> <chr>       <chr>  <chr>    <chr>  <chr>  \n1 1     0           libme…          1 6 to 10     secon… VA       South  US     \n2 2     0           class…          1 6 to 10     secon… FL       South  US     \n3 3     0           distr…          2 11 to 20    gener… PA       North… US     \n4 4     0           class…          2 11 to 20    middle NC       South  US     \n5 5     0           other…          3 20+         gener… AL       South  US     \n6 6     0           class…          1 4 to 5      gener… AL       South  US     \n# ℹ 4 more variables: group <chr>, gender <chr>, expert <chr>, connect <chr>\n```\n\n\n:::\n:::\n\n\n#### Step 3: Construct and Explore the Network\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build the directed network graph (nodes: uid, edges: sender->receiver)\ndlt1_network <- tbl_graph(\n  edges = dlt1_ties,\n  nodes = dlt1_actors,\n  node_key = \"uid\",\n  directed = TRUE\n)\n\n# Overview of the network\ndlt1_network\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tbl_graph: 445 nodes and 2529 edges\n#\n# A directed multigraph with 4 components\n#\n# Node Data: 445 × 13 (active)\n   uid   facilitator role1 experience experience2 grades location region country\n   <chr> <chr>       <chr>      <dbl> <chr>       <chr>  <chr>    <chr>  <chr>  \n 1 1     0           libm…          1 6 to 10     secon… VA       South  US     \n 2 2     0           clas…          1 6 to 10     secon… FL       South  US     \n 3 3     0           dist…          2 11 to 20    gener… PA       North… US     \n 4 4     0           clas…          2 11 to 20    middle NC       South  US     \n 5 5     0           othe…          3 20+         gener… AL       South  US     \n 6 6     0           clas…          1 4 to 5      gener… AL       South  US     \n 7 7     0           inst…          2 11 to 20    gener… SD       Midwe… US     \n 8 8     0           spec…          1 6 to 10     secon… BE       Inter… BE     \n 9 9     0           clas…          1 6 to 10     middle NC       South  US     \n10 10    0           scho…          2 11 to 20    middle NC       South  US     \n# ℹ 435 more rows\n# ℹ 4 more variables: group <chr>, gender <chr>, expert <chr>, connect <chr>\n#\n# Edge Data: 2,529 × 9\n   from    to timestamp    discussion_title  discussion_category parent_category\n  <int> <int> <chr>        <chr>             <chr>               <chr>          \n1   360   444 4/4/13 16:32 Most important c… Group N             Units 1-3 Disc…\n2   356   444 4/4/13 18:45 Most important c… Group D-L           Units 1-3 Disc…\n3   356   444 4/4/13 18:47 DLT Resources—Co… Group D-L           Units 1-3 Disc…\n# ℹ 2,526 more rows\n# ℹ 3 more variables: discussion_identifier <chr>, comment_id <chr>,\n#   discussion_id <chr>\n```\n\n\n:::\n:::\n\n\n#### Step 4: Basic Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quick overview plot (stress layout by default)\nautograph(dlt1_network)\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/visualize-network-dlt1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Custom visualization with colors and centrality\nggraph(dlt1_network, layout = \"fr\") +\n  geom_edge_link(alpha = .2) +\n  geom_node_point(aes(color = role1, size = local_size())) +\n  theme_graph() +\n  theme(text = element_text(family = \"sans\"))\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/visualize-network-dlt1-2.png){width=672}\n:::\n:::\n\n\n#### Step 5: Network Size and Centralization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of nodes and edges\ngorder(dlt1_network)   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 445\n```\n\n\n:::\n\n```{.r .cell-code}\ngsize(dlt1_network)    \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2529\n```\n\n\n:::\n\n```{.r .cell-code}\n# Degree centrality (all, in, out)\ndeg_all <- centr_degree(dlt1_network, mode = \"all\")$res\ndeg_in  <- centr_degree(dlt1_network, mode = \"in\")$res\ndeg_out <- centr_degree(dlt1_network, mode = \"out\")$res\n\n# Centralization\ncentr_degree(dlt1_network, mode = \"all\")$centralization  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6429242\n```\n\n\n:::\n\n```{.r .cell-code}\ncentr_degree(dlt1_network, mode = \"in\")$centralization   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.05702\n```\n\n\n:::\n\n```{.r .cell-code}\ncentr_degree(dlt1_network, mode = \"out\")$centralization  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2259389\n```\n\n\n:::\n:::\n\n\n#### Step 6: Attach and Visualize Node Centrality\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add in-degree centrality as node attribute\ndlt1_network <- dlt1_network |>\n  activate(nodes) |>\n  mutate(in_degree = centrality_degree(mode = \"in\"))\n\n# Plot, sizing nodes by in-degree\nggraph(dlt1_network, layout = \"fr\") +\n  geom_edge_link(alpha = .2) +\n  geom_node_point(aes(size = in_degree, color = role1)) +\n  theme_graph() +\n  theme(text = element_text(family = \"sans\"))\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/node-centrality-dlt1-1.png){width=672}\n:::\n:::\n\n\n#### Step 7: Network Density, Reciprocity, Clustering, Distance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Density\nedge_density(dlt1_network)      \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01279988\n```\n\n\n:::\n\n```{.r .cell-code}\n# Reciprocity\nreciprocity(dlt1_network)       \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1997544\n```\n\n\n:::\n\n```{.r .cell-code}\n# Add reciprocated edge attribute and plot\ndlt1_network <- dlt1_network |>\n  activate(edges) |>\n  mutate(reciprocated = edge_is_mutual())\n\nggraph(dlt1_network, layout = \"fr\") +\n  geom_node_point(aes(size = in_degree)) +\n  geom_edge_link(aes(color = reciprocated), alpha = .2) +\n  theme_graph() +\n  theme(text = element_text(family = \"sans\"))\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/network-stats-dlt1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Clustering (transitivity/global)\ntransitivity(dlt1_network)      \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08880774\n```\n\n\n:::\n\n```{.r .cell-code}\n# Network diameter (longest shortest path) & average distance\ndiameter(dlt1_network)          \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n\n```{.r .cell-code}\nmean_distance(dlt1_network)     \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.030694\n```\n\n\n:::\n:::\n\n\n#### Step 8: Repeat for DLT2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Load the DLT2 edge and node data\ndlt2_ties <- read_csv(\"data/dlt2-edges.csv\", \n  col_types = cols(Sender = col_character(), \n                   Receiver = col_character(), \n                   `Category Text` = col_skip(), \n                   `Comment ID` = col_character(), \n                   `Discussion ID` = col_character())) |> \n  clean_names()\n\ndlt2_actors <- read_csv(\"data/dlt2-nodes.csv\", \n  col_types = cols(UID = col_character(), \n                   Facilitator = col_character(), \n                   expert = col_character(), \n                   connect = col_character())) |> \n  clean_names()\n\n# 2. Construct the directed network\ndlt2_network <- tbl_graph(\n  edges = dlt2_ties,\n  nodes = dlt2_actors,\n  node_key = \"uid\",\n  directed = TRUE\n)\n\n# 3. Basic network properties\nnum_nodes <- gorder(dlt2_network)   \nnum_edges <- gsize(dlt2_network)    \n\n# 4. Degree centrality (overall, in, out)\ndeg_all <- centr_degree(dlt2_network, mode = \"all\")$res\ndeg_in  <- centr_degree(dlt2_network, mode = \"in\")$res\ndeg_out <- centr_degree(dlt2_network, mode = \"out\")$res\n\n# Centralization values\ncentr_all <- centr_degree(dlt2_network, mode = \"all\")$centralization\ncentr_in  <- centr_degree(dlt2_network, mode = \"in\")$centralization\ncentr_out <- centr_degree(dlt2_network, mode = \"out\")$centralization\n\n# 5. Attach centrality as a node attribute\ndlt2_network <- dlt2_network |>\n  activate(nodes) |>\n  mutate(in_degree = centrality_degree(mode = \"in\"))\n\n# 6. Visualize the network\nggraph(dlt2_network, layout = \"fr\") +\n  geom_edge_link(alpha = .2) +\n  geom_node_point(aes(color = role, size = local_size())) +\n  theme_graph() +\n  theme(text = element_text(family = \"sans\"))\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/analysis-dlt2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 7. Density, reciprocity, clustering, distances\ndensity <- edge_density(dlt2_network)\nrecip   <- reciprocity(dlt2_network)\n\ndlt2_network <- dlt2_network |>\n  activate(edges) |>\n  mutate(reciprocated = edge_is_mutual())\n\nggraph(dlt2_network, layout = \"fr\") +\n  geom_node_point(aes(size = in_degree)) +\n  geom_edge_link(aes(color = reciprocated), alpha = .2) +\n  theme_graph() +\n  theme(text = element_text(family = \"sans\"))\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/analysis-dlt2-2.png){width=672}\n:::\n\n```{.r .cell-code}\ntrans   <- transitivity(dlt2_network)\ndiam    <- diameter(dlt2_network)\nmean_d  <- mean_distance(dlt2_network)\n\n# 8. Print summary statistics\ncat(\"DLT2 Network Stats:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDLT2 Network Stats:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Nodes:\", num_nodes, \"Edges:\", num_edges, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodes: 492 Edges: 2584 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Degree Centralization (all/in/out):\", centr_all, centr_in, centr_out, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDegree Centralization (all/in/out): 0.5311161 0.8650671 0.3273889 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Density:\", density, \"Reciprocity:\", recip, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDensity: 0.0106966 Reciprocity: 0.2500977 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Transitivity:\", trans, \"Diameter:\", diam, \"Mean Distance:\", mean_d, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTransitivity: 0.1248291 Diameter: 8 Mean Distance: 3.03815 \n```\n\n\n:::\n:::\n\n\n### 3.3.4 Results and Discussion\n\n#### **RQ1: What is the overall structure of interaction in each cohort?**\n\n-   **DLT1** consists of **445 nodes** (participants) and **2529 edges** (directed interactions).\n-   **DLT2** has **492 nodes** and **2584 edges**.\n-   Both networks are **large and sparse**:\n    -   *Density*: DLT1 = **0.013**, DLT2 = **0.011**\n    -   Interpretation: Only about 1–1.3% of all possible connections exist—typical for online discussion networks where not every participant interacts with every other.\n-   Both networks are **multi-component** (several disconnected groups), but most participants are included in the main giant component.\n-   The **diameter** (longest shortest path) is 8 for both cohorts, and the **average shortest path length** is about **3.03 (DLT1)** and **3.04 (DLT2)**, indicating that on average, any participant is just 3 steps away from any other in the largest group.\n-   **Interpretation**: Information or discussion threads can reach most participants with only a few hops, but overall engagement is selective rather than comprehensive.\n\n#### **RQ2: Who are the most central or influential actors?**\n\n-   Centrality (degree, in-degree, out-degree) analyses show a **right-skewed distribution**: most participants have low centrality, but a small subset are highly connected.\n-   In both DLT1 and DLT2, **facilitators** and a handful of highly active participants emerge as **hubs**—they initiate and/or receive a disproportionate number of interactions.\n    -   For DLT1, degree centralization (all): **0.64** (in: **1.06**, out: **0.23**)\n    -   For DLT2, degree centralization (all): **0.53** (in: **0.87**, out: **0.33**)\n-   **Visualization**: Network plots with node size proportional to in-degree clearly highlight these central actors.\n-   **Interpretation**: These key individuals (often facilitators) play critical roles in steering discussion, providing feedback, and potentially keeping less active members engaged.\n\n#### **RQ3: Are ties reciprocated?**\n\n-   **Reciprocity** (proportion of mutual connections):\n    -   DLT1: **0.20** (20% of ties are reciprocated)\n    -   DLT2: **0.25** (25% reciprocated)\n-   **Interpretation**: Most interactions are one-way (e.g., a reply that does not receive a response), but a substantial fraction are mutual—possibly reflecting peer-to-peer conversations or ongoing exchanges. In online learning contexts, this suggests a mix of broadcasting (one-to-many) and genuine dialog (two-way).\n\n#### **RQ4: How cohesive are the networks?**\n\n-   **Transitivity/Clustering coefficient** (probability that two connected nodes’ neighbors are also connected):\n    -   DLT1: **0.089**\n    -   DLT2: **0.125**\n-   **Interpretation**: Triadic closure is low—there are few closed triangles, so close-knit groups (where “my friend is also your friend”) are rare. The network structure is more “hub-and-spoke” than “cliquish.”\n-   **Diameter**: 8 for both, showing that even the furthest nodes can be reached in 8 steps.\n-   **Mean distance**: \\~3.0, so participants are relatively close to each other in the main component.\n\n**Comparison Across Cohorts**\n\n-   **DLT2 is slightly larger** (more participants and interactions), but the structural properties—density, centralization, reciprocity, clustering, and path lengths—are all quite similar.\n-   Minor variations (e.g., higher reciprocity and clustering in DLT2) could reflect differences in facilitation style, cohort engagement, or participant composition.\n-   **Interpretation**: Both cohorts exhibit classic patterns for large-scale online educational discussions—a small number of central actors drive most of the interaction, the networks are sparse but efficiently connected, and genuine dialogue is present but not universal.\n\n**Educational Implications**\n\n-   **For educators and instructional designers**: These findings suggest that a small group of highly active facilitators or students are critical to fostering interaction. Encouraging more distributed engagement (for example, through peer response requirements or rotating leadership) may enhance network cohesion and learning opportunities.\n\n-   **For researchers**: Understanding who occupies central positions and the overall structure of discussion networks can inform interventions to support isolated participants, promote reciprocity, and create more connected learning communities.\n\n**Summary:**\n\nThrough these SNA measures, we have shown how to reconstruct, visualize, and interpret the structure of large-scale online discussion networks. The approach enables identification of core communicators, understanding of participation patterns, and empirical comparison across cohorts or interventions. This “cookbook” can be adapted to other online learning or collaborative contexts.\n\n::: callout-note\n## Note\n\nThis analysis is based on real-world data from online professional development courses. The methods and findings can be generalized to other educational settings where social networks play a role in learning and collaboration.\n:::\n\n## 3.4 Case Study: Hashtag Common Core\n\n### 3.4.1 Purpose & Case\n\nThe purpose of this case study is to demonstrate the application of social network analysis (SNA) in a real-world policy context: the heated national debate over the Common Core State Standards (CCSS) as it played out on Twitter. Drawing on the work of Supovitz, Daly, del Fresno, and Kolouch, the #COMMONCORE Project provides a vivid example of how social media-enabled networks shape educational discourse and policy.\n\nThis case focuses on: - Identifying **key actors** (“transmitters,” “transceivers,” and “transcenders”) and measuring their influence. - Detecting **subgroups/factions** within the conversation. - Exploring how **sentiment** about the Common Core varies across network positions. - Demonstrating **network wrangling, visualization, and analysis** using real tweet data.\n\n#### Data Source\n\nData was collected from Twitter’s public API using keywords/hashtags related to the Common Core (e.g., `#commoncore`, `ccss`, `stopcommoncore`). The dataset includes user names, tweets, mentions, retweets, and relevant timestamps from a sample week. Only public tweets are included, and user privacy is respected.\n\n### 3.4.2 Sample Research Questions\n\n-   **RQ1:** Who are the “transmitters,” “transceivers,” and “transcenders” in the Common Core Twitter network?\n-   **RQ2:** What subgroups or factions exist within the network, and how are they structured?\n-   **RQ3:** How does sentiment about the Common Core vary across actors and subgroups?\n-   **RQ4:** What other patterns of communication (e.g., centrality, clique formation, isolates) characterize this network?\n\n### 3.4.3 Analysis\n\n#### Step 1: Load Required Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) \nlibrary(tidygraph) \nlibrary(ggraph) \nlibrary(skimr) \nlibrary(igraph) \nlibrary(tidytext) \nlibrary(vader)\n```\n:::\n\n\n#### Step 2: Data Import and Wrangling\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import tweet data (edgelist format: sender, receiver, timestamp, text)\nccss_tweets <- read_csv(\"data/ccss-tweets.csv\")\n\n# Prepare the edgelist (extract sender, mentioned users, and tweet text)\nties_1 <- ccss_tweets |>\n  relocate(sender = screen_name, target = mentions_screen_name) |>\n  select(sender, target, created_at, text)\n\n# Unnest receiver to handle multiple mentions per tweet\nties_2 <- ties_1 |>\n  unnest_tokens(input = target,\n                output = receiver,\n                to_lower = FALSE) |>\n  relocate(sender, receiver)\n\n# Remove tweets without mentions to focus on direct connections\nties <- ties_2 |>\n  drop_na(receiver)\n\n# Build nodelist\nactors <- ties |>\n  select(sender, receiver) |>\n  pivot_longer(cols = c(sender, receiver), names_to = \"role\", values_to = \"actors\") |>\n  select(actors) |>\n  distinct()\n\n# Create Network Object\nccss_network <- tbl_graph(edges = ties,\n                          nodes = actors,\n                          directed = TRUE)\nccss_network\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tbl_graph: 46 nodes and 42 edges\n#\n# A directed multigraph with 14 components\n#\n# Node Data: 46 × 1 (active)\n   actors        \n   <chr>         \n 1 DistanceLrnBot\n 2 k12movieguides\n 3 WEquilSchool  \n 4 JoeWEquil     \n 5 SumayLu       \n 6 fluttbot      \n 7 BodShameless  \n 8 Math          \n 9 ozsultan      \n10 sfchronicle   \n# ℹ 36 more rows\n#\n# Edge Data: 42 × 4\n   from    to created_at          text                                          \n  <int> <int> <dttm>              <chr>                                         \n1     1     2 2021-06-28 09:53:54 \"#Luca Movie Guide | Worksheet | Questions | …\n2     3     4 2021-06-28 02:32:59 \"Why public schools should focus more on buil…\n3     3     3 2021-06-28 02:32:59 \"Why public schools should focus more on buil…\n# ℹ 39 more rows\n```\n\n\n:::\n:::\n\n\n#### Step 4: Network Structure – Components, Cliques, and Communities\n\n-   **Components** Identify weak and strong components (connected subgroups):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nccss_network <- ccss_network |>\n  activate(nodes) |>\n  mutate(weak_component = group_components(type = \"weak\"),\n         strong_component = group_components(type = \"strong\"))\n\n# View component sizes\nccss_network |>\n  as_tibble() |>\n  group_by(weak_component) |>\n  summarise(size = n()) |>\n  arrange(desc(size))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 14 × 2\n   weak_component  size\n            <int> <int>\n 1              1    14\n 2              2     6\n 3              3     4\n 4              4     3\n 5              5     3\n 6              6     2\n 7              7     2\n 8              8     2\n 9              9     2\n10             10     2\n11             11     2\n12             12     2\n13             13     1\n14             14     1\n```\n\n\n:::\n:::\n\n\n-   **Cliques** Identify fully connected subgroups (if any):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclique_num(ccss_network)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\ncliques(ccss_network, min = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n+ 3/46 vertices, from 8844029:\n[1] 4 5 6\n\n[[2]]\n+ 3/46 vertices, from 8844029:\n[1] 39 40 41\n\n[[3]]\n+ 3/46 vertices, from 8844029:\n[1] 3 4 6\n\n[[4]]\n+ 4/46 vertices, from 8844029:\n[1] 3 4 5 6\n\n[[5]]\n+ 3/46 vertices, from 8844029:\n[1] 3 4 5\n\n[[6]]\n+ 3/46 vertices, from 8844029:\n[1] 3 5 6\n```\n\n\n:::\n:::\n\n\n-   **Communities** Detect densely connected communities using edge betweenness:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nccss_network <- ccss_network |>\n  morph(to_undirected) |>\n  activate(nodes) |>\n  mutate(sub_group = group_edge_betweenness()) |>\n  unmorph()\n\nccss_network |>\n  as_tibble() |>\n  group_by(sub_group) |>\n  summarise(size = n()) |>\n  arrange(desc(size))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 2\n   sub_group  size\n       <int> <int>\n 1         1    10\n 2         2     6\n 3         3     4\n 4         4     3\n 5         5     3\n 6         6     2\n 7         7     2\n 8         8     2\n 9         9     2\n10        10     2\n11        11     2\n12        12     2\n13        13     2\n14        14     2\n15        15     1\n16        16     1\n```\n\n\n:::\n:::\n\n\n#### Step 5: Egocentric Analysis – Centrality & Key Actors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nccss_network <- ccss_network |>\n  activate(nodes) |>\n  mutate(\n    size = local_size(),\n    in_degree = centrality_degree(mode = \"in\"),\n    out_degree = centrality_degree(mode = \"out\"),\n    closeness = centrality_closeness(),\n    betweenness = centrality_betweenness()\n  )\n\n# Identify top actors by out_degree (transmitters), in_degree (transceivers), and both (transcenders)\ntop_transmitters <- ccss_network |> as_tibble() |> arrange(desc(out_degree)) |> head(5)\ntop_transceivers <- ccss_network |> as_tibble() |> arrange(desc(in_degree)) |> head(5)\n\n# Transcenders: high in-degree AND out-degree (using top 10% threshold)\ntop_transcenders <- ccss_network |> as_tibble() |>\n  filter(out_degree > quantile(out_degree, 0.9) & in_degree > quantile(in_degree, 0.9))\n```\n:::\n\n\n#### Step 6: Visualize the Network\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggraph(ccss_network, layout = \"fr\") +\n  geom_node_point(aes(size = out_degree, color = out_degree)) +\n  geom_edge_link(alpha = .2) +\n  theme_graph() +\n  theme(text = element_text(family = \"sans\"))\n```\n\n::: {.cell-output-display}\n![](chapter-3_files/figure-html/visualize-ccss-1.png){width=672}\n:::\n:::\n\n\n#### Step 7: Sentiment Analysis (Optional)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vader)\nvader_ccss <- vader_df(ccss_tweets$text)\nmean(vader_ccss$compound)\n\nvader_ccss_summary <- vader_ccss |>\n  mutate(sentiment = case_when(\n    compound >= 0.05 ~ \"positive\",\n    compound <= -0.05 ~ \"negative\",\n    TRUE ~ \"neutral\"\n  )) |>\n  count(sentiment)\n```\n:::\n\n\n### 3.4.4 Results and Discussion\n\n#### **RQ1: Who are the “transmitters,” “transceivers,” and “transcenders” in the Common Core Twitter network?**\n\n-   **Transmitters (high out-degree):** The user `SumayLu` stands out as the top transmitter, initiating 8 outgoing ties (mentions/retweets), followed by `DouglasHolt...` (5), `WEquilSchool` (3), `fluttbot` (3), and `JoeWEquil` (2). These users are the most active in broadcasting or mentioning others within the network.\n\n-   **Transceivers (high in-degree):** The most-mentioned users are `WEquilSchool` and `SumayLu` (in-degree = 3), `JoeWEquil` (2), `Tech4Learni...` (2), and `LASER_Insti...` (2). These individuals receive the most attention from other actors—potential focal points in conversations.\n\n-   **Transcenders (high in-degree *and* out-degree):** Only two users—`WEquilSchool` (in-degree = 3, out-degree = 3) and `SumayLu` (in-degree = 3, out-degree = 8)—simultaneously act as hubs for both sending and receiving communication. These “bridging” actors may serve as key facilitators or connectors in the discourse.\n\n#### **RQ2: What subgroups or factions exist in the network?**\n\n-   **Component analysis** shows a **fragmented network**:\n    -   There are **14 weakly connected components**, the largest containing 14 users, and several small groups or dyads (many with just 2–3 members).\n    -   This fragmentation suggests limited overall cohesion, with multiple parallel or isolated conversations occurring.\n-   **Clique analysis** reveals:\n    -   Four cliques (fully connected subgroups) of size 3 or 4—e.g., one 4-person clique involving nodes 3, 4, 5, and 6, and several overlapping 3-person cliques. This indicates pockets of tight-knit interaction, but such groups are rare relative to the size of the network.\n-   **Community detection** using edge betweenness identifies 16 subgroups, generally aligning with the component structure. The largest subgroup has 10 members, with most others much smaller.\n\n#### **RQ3: What is the overall sentiment in the network?**\n\n-   **VADER sentiment analysis** of tweet content yields:\n    -   An average sentiment score (`compound`) of **0.09** (slightly positive), indicating that, despite the policy controversy, the sampled tweets were, on balance, more positive than negative.\n    -   When tweets are classified into categories, a mix of *positive*, *neutral*, and *negative* tweets is observed, with positive tweets slightly outnumbering negatives.\n    -   This suggests the debate, at least in this time slice, included advocacy and constructive dialogue, not only criticism or negativity.\n\n#### **RQ4: What other patterns of communication (e.g., centrality, clique formation, isolates) characterize this network?**\n\n-   **Centrality Patterns:** The network displays a classic \"star\" structure in its largest component. Two users, `SumayLu` and `WEquilSchool`, stand out with high out-degree and in-degree centrality, respectively. Most other users have very low degree values (often 0 or 1), meaning they are peripheral, engaging in few interactions.\n\n-   **Clique Formation:** Clique analysis revealed **4 cliques** (fully connected subgroups) of size 3 or more, with one larger clique (size 4) and several overlapping smaller cliques. However, cliques are rare and limited in size—most communication occurs outside of dense subgroups.\n\n-   **Isolates and Components:** The network has **14 weak components**—many of them tiny. Several users are **isolates** or part of isolated dyads and triads, meaning they are disconnected from the main conversation or only loosely connected. This points to a lack of broad, network-wide cohesion.\n\n-   **Summary:** Communication in this network is characterized by strong centralization around a small number of users (hubs), a sparse and fragmented structure with many small, disconnected components, and numerous isolates.\n\n#### **Discussion**\n\nThis analysis of the Common Core Twitter conversation reveals a **sparse and fragmented network structure**. The debate is distributed across many small subgroups, with only one moderately sized component.\n\n-   **Key actors** serve as broadcasters and focal points, but most users are peripheral.\n-   **Cliques and communities** are few and small, underscoring the lack of broad cohesion.\n-   **Sentiment** is slightly positive on average, reflecting the presence of advocacy and promotional messaging.\n\n**Implications:** For researchers and practitioners, identifying and engaging “transcenders” is essential for bridging subgroups. Outreach should consider the network’s fragmentation—broader influence may require engaging multiple small groups individually rather than targeting a single “core.” Combining SNA with sentiment analysis gives a fuller picture: not just who is talking, but *how* and *with what tone*.\n\n**References**\n\n-   Supovitz, J., Daly, A.J., del Fresno, M., & Kolouch, C. (2017). *#commoncore Project.* Retrieved from [http://www.hashtagcommoncore.com](http://www.hashtagcommoncore.com/)\n\n-   Carolan, B.V. (2014). *Social Network Analysis and Education: Theory, Methods & Applications.* Sage.\n\n-   Silge, J., & Robinson, D. (2017). *Text Mining with R: A Tidy Approach*. O’Reilly.",
    "supporting": [
      "chapter-3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}