<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Numeric Data – Computational Analysis of Educational Data: A Field Guide Using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./section-3-intro.html" rel="next">
<link href="./chapter-3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e22fca9baa702f495ffd48617094d5fd.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-26a26002a694bedc01fedf658a62bff0.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e22fca9baa702f495ffd48617094d5fd.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-014a3776061e65346dda3980121eb167.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-b1fd978b70a8f69ce09fb519968ad8ed.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-014a3776061e65346dda3980121eb167.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles/override.css">
<link rel="stylesheet" href="styles/sidebar.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./section-2-Intro.html">Computational Methods</a></li><li class="breadcrumb-item"><a href="./chapter-4.html"><span class="chapter-title">Numeric Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Computational Analysis of Educational Data: A Field Guide Using R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1-1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Positron and RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1-2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1-3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1-4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LLMs and Data Science</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section-2-Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Computational Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Text Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Networks Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-4.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Numeric Data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./section-3-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LLMs Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-6.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Local LLMs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-7.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Image Data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Communication</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-8.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Communication</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Conclusion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">4.1 Overview</a></li>
  <li><a href="#accessing-big-data-broadening-the-horizon" id="toc-accessing-big-data-broadening-the-horizon" class="nav-link" data-scroll-target="#accessing-big-data-broadening-the-horizon">4.2 Accessing Big data (Broadening the Horizon)</a>
  <ul class="collapse">
  <li><a href="#big-data" id="toc-big-data" class="nav-link" data-scroll-target="#big-data">4.2.1 Big Data</a></li>
  <li><a href="#learning-analytics" id="toc-learning-analytics" class="nav-link" data-scroll-target="#learning-analytics">4.2.2 Learning Analytics</a></li>
  </ul></li>
  <li><a href="#logistic-regression-ml" id="toc-logistic-regression-ml" class="nav-link" data-scroll-target="#logistic-regression-ml">4.3 Logistic Regression ML</a>
  <ul class="collapse">
  <li><a href="#purpose-case" id="toc-purpose-case" class="nav-link" data-scroll-target="#purpose-case">4.3.1 Purpose + CASE</a></li>
  <li><a href="#sample-research-questions-rqs" id="toc-sample-research-questions-rqs" class="nav-link" data-scroll-target="#sample-research-questions-rqs">4.3.2 Sample Research Questions (RQs)</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">4.3.3 Analysis</a></li>
  <li><a href="#results-and-discussions" id="toc-results-and-discussions" class="nav-link" data-scroll-target="#results-and-discussions">4.3.4 Results and Discussions</a></li>
  </ul></li>
  <li><a href="#random-forests-ml-on-interactions-data" id="toc-random-forests-ml-on-interactions-data" class="nav-link" data-scroll-target="#random-forests-ml-on-interactions-data">4.4 Random Forests ML on Interactions Data</a>
  <ul class="collapse">
  <li><a href="#purpose-case-1" id="toc-purpose-case-1" class="nav-link" data-scroll-target="#purpose-case-1">4.4.1 Purpose + CASE</a></li>
  <li><a href="#sample-research-questions" id="toc-sample-research-questions" class="nav-link" data-scroll-target="#sample-research-questions">4.4.2 Sample Research Questions</a></li>
  <li><a href="#analysis-1" id="toc-analysis-1" class="nav-link" data-scroll-target="#analysis-1">4.4.3 Analysis</a></li>
  <li><a href="#results-and-discussions-1" id="toc-results-and-discussions-1" class="nav-link" data-scroll-target="#results-and-discussions-1">4.4.4 Results and Discussions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./section-2-Intro.html">Computational Methods</a></li><li class="breadcrumb-item"><a href="./chapter-4.html"><span class="chapter-title">Numeric Data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Numeric Data</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Abstract:</strong> This section reviews how to access data that is primarily numeric/quantitative in nature, but from a different source and of a different nature than the data typically used by social scientists. Example data sets include international or national large-scale assessments (e.g., PISA, NAEP，IPEDS) and data from digital technologies (e.g., log-trace data from Open University Learning Analytics Dataset (OULAD)).&nbsp;</p>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">4.1 Overview</h2>
<p>In social science research, data is traditionally sourced from small-scale surveys, experiments, or qualitative studies. However, the rise of big data offers researchers opportunities to explore numeric and quantitative datasets of unprecedented scale and variety. This chapter discusses how to access and analyze large-scale datasets like international assessments (e.g., PISA, NAEP) and digital log-trace data (e.g., Open University Learning Analytics Dataset (OULAD)). These secondary data sources enable novel research questions and methods, particularly when paired with machine learning and statistical modeling approaches.</p>
</section>
<section id="accessing-big-data-broadening-the-horizon" class="level2">
<h2 class="anchored" data-anchor-id="accessing-big-data-broadening-the-horizon">4.2 Accessing Big data (Broadening the Horizon)</h2>
<section id="big-data" class="level3">
<h3 class="anchored" data-anchor-id="big-data">4.2.1 Big Data</h3>
<section id="accessing-pisa-data" class="level4">
<h4 class="anchored" data-anchor-id="accessing-pisa-data">Accessing PISA Data</h4>
<p>The Programme for International Student Assessment (PISA) is a widely used dataset for large-scale educational research. It assesses 15-year-old students’ knowledge and skills in reading, mathematics, and science across multiple countries. Researchers can access PISA data through various methods:</p>
<section id="direct-download-from-the-official-website" class="level5">
<h5 class="anchored" data-anchor-id="direct-download-from-the-official-website">1. <strong>Direct Download from the Official Website</strong></h5>
<p>The OECD provides direct access to PISA data files via its official website. Researchers can download data for specific years and cycles. Data files are typically provided in <code>.csv</code> or <code>.sav</code> (SPSS) formats, along with detailed documentation.</p>
<ul>
<li><strong>Steps to Access PISA Data from the OECD Website:</strong>
<ol type="1">
<li>Visit the <a href="https://www.oecd.org/pisa/">OECD PISA website</a>.</li>
<li>Navigate to the “Data” section.</li>
<li>Select the desired assessment year (e.g., 2022).</li>
<li>Download the data and accompanying codebooks.</li>
</ol></li>
</ul>
</section>
<section id="using-the-oecd-r-package" class="level5">
<h5 class="anchored" data-anchor-id="using-the-oecd-r-package">2. <strong>Using the <code>OECD</code> R Package</strong></h5>
<p>The <code>OECD</code> R package provides a direct interface to download and explore datasets published by the OECD, including PISA.</p>
<ul>
<li><strong>Steps to Use the <code>OECD</code> Package:</strong>
<ol type="1">
<li>Install and load the <code>OECD</code> package.</li>
<li>Use the <code>getOECD()</code> function to fetch PISA data.</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the OECD package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"OECD"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(OECD)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fetch PISA data for the 2018 cycle</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>pisa_data <span class="ot">&lt;-</span> <span class="fu">getOECD</span>(<span class="st">"pisa"</span>, <span class="at">years =</span> <span class="st">"2022"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display a summary of the data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pisa_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-the-edsurvey-r-package" class="level5">
<h5 class="anchored" data-anchor-id="using-the-edsurvey-r-package">3. <strong>Using the <code>Edsurvey</code> R Package</strong></h5>
<p>The <code>Edsurvey</code> package is designed specifically for analyzing large-scale assessment data, including PISA. It allows for complex statistical modeling and supports handling weights and replicate weights used in PISA.</p>
<ul>
<li><strong>Steps to Use the <code>Edsurvey</code> Package:</strong>
<ol type="1">
<li>Install and load the <code>Edsurvey</code> package.</li>
<li>Download the PISA data from the OECD website and provide the path to the <code>.sav</code> files.</li>
<li>Load the data into R using <code>readPISA()</code>.</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the Edsurvey package</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"Edsurvey"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Edsurvey)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Read PISA data from a local file</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>pisa_data <span class="ot">&lt;-</span> <span class="fu">readPISA</span>(<span class="st">"path/to/PISA2022Student.sav"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the structure of the dataset</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pisa_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="comparison-of-methods" class="level5">
<h5 class="anchored" data-anchor-id="comparison-of-methods">Comparison of Methods</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Method</strong></th>
<th><strong>Advantages</strong></th>
<th><strong>Disadvantages</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Direct Download</td>
<td>Full access to all raw data and documentation.</td>
<td>Requires manual processing and cleaning.</td>
</tr>
<tr class="even">
<td><code>OECD</code> Package</td>
<td>Easy to use for downloading specific datasets.</td>
<td>Limited to OECD-published formats.</td>
</tr>
<tr class="odd">
<td><code>Edsurvey</code> Package</td>
<td>Supports advanced statistical analysis and weights.</td>
<td>Requires additional setup and dependencies.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="accessing-ipeds-data" class="level4">
<h4 class="anchored" data-anchor-id="accessing-ipeds-data">Accessing IPEDS Data</h4>
<p>The Integrated Postsecondary Education Data System (IPEDS) is a comprehensive source of data on U.S. colleges, universities, and technical and vocational institutions. It provides data on enrollments, completions, graduation rates, faculty, finances, and more. Researchers and policymakers widely use IPEDS data to analyze trends in higher education.</p>
<p>There are several ways to access IPEDS data, depending on the user’s needs and technical proficiency.</p>
<section id="direct-download-from-the-nces-website" class="level5">
<h5 class="anchored" data-anchor-id="direct-download-from-the-nces-website">1. <strong>Direct Download from the NCES Website</strong></h5>
<p>The most straightforward way to access IPEDS data is by downloading it directly from the National Center for Education Statistics (NCES) website.</p>
</section>
<section id="steps-to-access-ipeds-data" class="level5">
<h5 class="anchored" data-anchor-id="steps-to-access-ipeds-data"><strong>Steps to Access IPEDS Data:</strong></h5>
<ol type="1">
<li>Visit the <a href="https://nces.ed.gov/ipeds/">IPEDS Data Center</a>.</li>
<li>Click on “Use the Data” and navigate to the “Download IPEDS Data Files” section.</li>
<li>Select the desired data year and survey component (e.g., Fall Enrollment, Graduation Rates).</li>
<li>Download the data files, typically provided in <code>.csv</code> or <code>.xls</code> format, along with accompanying codebooks.</li>
</ol>
</section>
<section id="using-the-ipeds-r-package" class="level5">
<h5 class="anchored" data-anchor-id="using-the-ipeds-r-package">2. <strong>Using the <code>ipeds</code> R Package</strong></h5>
<p>The <code>ipeds</code> R package simplifies downloading and analyzing IPEDS data directly from R by connecting to the NCES data repository.</p>
</section>
<section id="steps-to-use-the-ipeds-package" class="level5">
<h5 class="anchored" data-anchor-id="steps-to-use-the-ipeds-package"><strong>Steps to Use the <code>ipeds</code> Package:</strong></h5>
<ol type="1">
<li>Install and load the <code>ipeds</code> package.</li>
<li>Use the <code>download_ipeds()</code> function to fetch data for specific survey components and years.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the ipeds package</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ipeds"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ipeds)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Download IPEDS data for completions in 2021</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>ipeds_data <span class="ot">&lt;-</span> <span class="fu">download_ipeds</span>(<span class="st">"C"</span>, <span class="at">year =</span> <span class="dv">2021</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># View the structure of the downloaded data</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(ipeds_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-the-tidycensus-r-package" class="level5">
<h5 class="anchored" data-anchor-id="using-the-tidycensus-r-package">3. <strong>Using the <code>tidycensus</code> R Package</strong></h5>
<p>The <code>tidycensus</code> package, while primarily designed for Census data, can access specific IPEDS data linked to educational institutions.</p>
</section>
<section id="steps-to-use-the-tidycensus-package" class="level5">
<h5 class="anchored" data-anchor-id="steps-to-use-the-tidycensus-package"><strong>Steps to Use the <code>tidycensus</code> Package:</strong></h5>
<ol type="1">
<li>Install and load the <code>tidycensus</code> package.</li>
<li>Set up a Census API key to access the data.</li>
<li>Query IPEDS data for specific institution-level information.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the tidycensus package</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidycensus"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set Census API key (replace with your actual key)</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">census_api_key</span>(<span class="st">"your_census_api_key"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Fetch IPEDS-related data (e.g., institution information)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>ipeds_institutions <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"place"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">"B14002_003"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2021</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ipeds_institutions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-online-tools" class="level5">
<h5 class="anchored" data-anchor-id="using-online-tools">4. <strong>Using Online Tools</strong></h5>
<p>IPEDS provides several online tools for querying and visualizing data without requiring programming skills.</p>
</section>
<section id="common-tools" class="level5">
<h5 class="anchored" data-anchor-id="common-tools"><strong>Common Tools:</strong></h5>
<ul>
<li><strong>IPEDS Data Explorer</strong>: Enables users to query and export customized datasets.</li>
<li><strong>Trend Generator</strong>: Allows users to visualize trends in key metrics over time.</li>
<li><strong>IPEDS Use the Data</strong>: Simplified tool for accessing pre-compiled datasets.</li>
</ul>
</section>
<section id="steps-to-use-the-ipeds-data-explorer" class="level5">
<h5 class="anchored" data-anchor-id="steps-to-use-the-ipeds-data-explorer"><strong>Steps to Use the IPEDS Data Explorer:</strong></h5>
<ol type="1">
<li>Visit the IPEDS Data Explorer.</li>
<li>Select variables of interest, such as institution type, enrollment size, or location.</li>
<li>Filter results by years, institution categories, or other criteria.</li>
<li>Export the results as a <code>.csv</code> or <code>.xlsx</code> file.</li>
</ol>
</section>
<section id="comparison-of-methods-1" class="level5">
<h5 class="anchored" data-anchor-id="comparison-of-methods-1">Comparison of Methods</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Method</strong></th>
<th><strong>Advantages</strong></th>
<th><strong>Disadvantages</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Direct Download</td>
<td>Full access to raw data and documentation.</td>
<td>Requires manual data preparation and cleaning.</td>
</tr>
<tr class="even">
<td><code>ipeds</code> Package</td>
<td>Automated access to specific components.</td>
<td>Limited flexibility for customized queries.</td>
</tr>
<tr class="odd">
<td><code>tidycensus</code> Package</td>
<td>Allows integration with Census and ACS data.</td>
<td>Requires API setup and advanced R skills.</td>
</tr>
<tr class="even">
<td>Online Tools</td>
<td>User-friendly and suitable for non-coders.</td>
<td>Limited to predefined queries and exports.</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="accessing-open-university-learning-analytics-dataset-oulad" class="level4">
<h4 class="anchored" data-anchor-id="accessing-open-university-learning-analytics-dataset-oulad">Accessing Open University Learning Analytics Dataset (OULAD)</h4>
<p>The <strong>Open University Learning Analytics Dataset (OULAD)</strong> is a publicly available dataset designed to support research in educational data mining and learning analytics. It includes student demographics, module information, interactions with the virtual learning environment (VLE), and assessment scores.</p>
</section>
<section id="steps-to-access-oulad-data" class="level4">
<h4 class="anchored" data-anchor-id="steps-to-access-oulad-data">Steps to Access OULAD Data</h4>
<section id="visit-the-oulad-repository" class="level5">
<h5 class="anchored" data-anchor-id="visit-the-oulad-repository">Visit the OULAD Repository**</h5>
<p>The dataset is hosted on the <a href="https://analyse.kmi.open.ac.uk/open_dataset">Open University’s Analytics Project</a>. To access the data: 1. Navigate to the website. 2. Download the dataset as a <code>.zip</code> file. 3. Extract the <code>.zip</code> file to a local directory.</p>
<p>The dataset contains multiple CSV files: - <code>studentInfo.csv</code>: Student demographics and performance data. - <code>studentVle.csv</code>: Interactions with the VLE. - <code>vle.csv</code>: Details of learning resources. - <code>studentAssessment.csv</code>: Assessment scores.</p>
</section>
<section id="loading-oulad-data-in-r" class="level5">
<h5 class="anchored" data-anchor-id="loading-oulad-data-in-r">Loading OULAD Data in R</h5>
<p>Once the data is downloaded and extracted, follow these steps to load and access it in R:</p>
</section>
<section id="step-1-install-required-packages" class="level5">
<h5 class="anchored" data-anchor-id="step-1-install-required-packages"><strong>Step 1: Install Required Packages</strong></h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install necessary packages</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"readr"</span>, <span class="st">"dplyr"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2-load-data" class="level5">
<h5 class="anchored" data-anchor-id="step-2-load-data"><strong>Step 2: Load Data</strong></h5>
<p>Use the <code>readr</code> package to read the CSV files into R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the path to the OULAD data</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> <span class="st">"path/to/OULAD/"</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load individual CSV files</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>student_info <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">file.path</span>(data_path, <span class="st">"studentInfo.csv"</span>))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>student_vle <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">file.path</span>(data_path, <span class="st">"studentVle.csv"</span>))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>vle <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">file.path</span>(data_path, <span class="st">"vle.csv"</span>))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>student_assessment <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">file.path</span>(data_path, <span class="st">"studentAssessment.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-3-preview-the-data" class="level5">
<h5 class="anchored" data-anchor-id="step-3-preview-the-data"><strong>Step 3: Preview the Data</strong></h5>
<p>Inspect the structure and contents of the datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows of student info</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(student_info)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the structure of the student VLE data</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(student_vle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="learning-analytics" class="level3">
<h3 class="anchored" data-anchor-id="learning-analytics">4.2.2 Learning Analytics</h3>
<section id="what-is-learning-analytics" class="level4">
<h4 class="anchored" data-anchor-id="what-is-learning-analytics">What is Learning Analytics?</h4>
<p><strong>Learning Analytics (LA)</strong> refers to the measurement, collection, analysis, and reporting of data about learners and their contexts. The primary goal of LA is to understand and improve learning processes by identifying patterns, predicting outcomes, and providing actionable insights to educators, institutions, and learners.</p>
<p>Key features of LA include: - <strong>Data Collection</strong>: Gathering information from digital platforms such as learning management systems (LMS) or external assessments. - <strong>Analysis</strong>: Using machine learning, statistical methods, or visualization tools to reveal trends and patterns. - <strong>Applications</strong>: Supporting personalized learning, enhancing institutional decision-making, and improving curriculum design.</p>
</section>
<section id="applications-of-learning-analytics-in-big-data" class="level4">
<h4 class="anchored" data-anchor-id="applications-of-learning-analytics-in-big-data">Applications of Learning Analytics in Big Data</h4>
<p>Learning analytics can be applied to large-scale educational datasets like <strong>PISA</strong>, <strong>IPEDS</strong>, and <strong>OULAD</strong> to uncover trends, predict outcomes, and guide interventions.</p>
<section id="pisa-data-and-learning-analytics" class="level5">
<h5 class="anchored" data-anchor-id="pisa-data-and-learning-analytics"><strong>1. PISA Data and Learning Analytics</strong></h5>
<ul>
<li><strong>What it offers</strong>: Insights into international student performance in reading, math, and science, combined with contextual variables (e.g., socio-economic status).</li>
<li><strong>LA Applications</strong>:
<ul>
<li>Identifying key factors influencing performance across countries.</li>
<li>Predicting the impact of ICT use on student achievement.</li>
<li>Segmenting students into performance clusters for targeted interventions.</li>
</ul></li>
</ul>
</section>
<section id="ipeds-data-and-learning-analytics" class="level5">
<h5 class="anchored" data-anchor-id="ipeds-data-and-learning-analytics"><strong>2. IPEDS Data and Learning Analytics</strong></h5>
<ul>
<li><strong>What it offers</strong>: U.S. institutional-level data on enrollment, graduation rates, tuition, and financial aid.</li>
<li><strong>LA Applications</strong>:
<ul>
<li>Analyzing trends in student demographics across institutions.</li>
<li>Predicting enrollment patterns based on historical data.</li>
<li>Benchmarking institutions to inform policymaking and funding decisions.</li>
</ul></li>
</ul>
</section>
<section id="oulad-and-learning-analytics" class="level5">
<h5 class="anchored" data-anchor-id="oulad-and-learning-analytics"><strong>3. OULAD and Learning Analytics</strong></h5>
<ul>
<li><strong>What it offers</strong>: Rich data on student engagement with virtual learning environments (VLE), assessment scores, and demographic information.</li>
<li><strong>LA Applications</strong>:
<ul>
<li>Tracking student interactions with learning resources to predict course completion.</li>
<li>Modeling the relationship between VLE usage and final grades.</li>
<li>Detecting early warning signs for at-risk students based on engagement metrics.</li>
</ul></li>
</ul>
</section>
</section>
<section id="why-learning-analytics-matters" class="level4">
<h4 class="anchored" data-anchor-id="why-learning-analytics-matters">Why Learning Analytics Matters</h4>
<p>The integration of <strong>Learning Analytics</strong> with big data enables researchers and practitioners to: - <strong>Personalize Learning</strong>: Tailor educational experiences to meet individual needs. - <strong>Improve Retention</strong>: Identify at-risk learners and implement timely interventions. - <strong>Enhance Decision-Making</strong>: Provide evidence-based recommendations for curriculum and policy adjustments.</p>
<p>By leveraging datasets like PISA, IPEDS, and OULAD, learning analytics can help bridge the gap between raw data and actionable insights, fostering a more equitable and effective educational landscape.</p>
</section>
<section id="supervised-learning-in-learning-analytics" class="level4">
<h4 class="anchored" data-anchor-id="supervised-learning-in-learning-analytics">Supervised Learning in Learning Analytics</h4>
<p>Machine Learning, particularly <strong>Supervised Learning</strong>, has become a cornerstone of Learning Analytics. Supervised learning models are trained on labeled datasets, where input features are mapped to known outcomes, enabling the prediction of new, unseen data.</p>
<section id="key-concepts-in-supervised-learning" class="level5">
<h5 class="anchored" data-anchor-id="key-concepts-in-supervised-learning">Key Concepts in Supervised Learning</h5>
<ul>
<li><p><strong>Definition</strong><br>
Supervised Learning is a subset of Machine Learning focused on learning a mapping between input variables (features) and output variables (labels or outcomes). Models trained on labeled data can predict outcomes for new data points.</p></li>
<li><p><strong>Common Algorithms</strong></p>
<ul>
<li>Linear Regression</li>
<li>Logistic Regression</li>
<li>Decision Trees and Random Forests</li>
<li>Neural Networks</li>
</ul></li>
<li><p><strong>Applications in Education</strong><br>
Supervised learning is particularly effective in Learning Analytics for predicting:</p>
<ul>
<li>Student performance</li>
<li>Dropout risks</li>
<li>Enrollment trends</li>
<li>Course completion rates</li>
</ul></li>
</ul>
</section>
</section>
<section id="applications-of-supervised-learning-with-big-data" class="level4">
<h4 class="anchored" data-anchor-id="applications-of-supervised-learning-with-big-data">Applications of Supervised Learning with Big Data</h4>
<section id="pisa-data-and-supervised-learning" class="level5">
<h5 class="anchored" data-anchor-id="pisa-data-and-supervised-learning"><strong>1. PISA Data and Supervised Learning</strong></h5>
<ul>
<li><strong>Goal</strong>: Use demographic and contextual features to predict student performance in mathematics, reading, or science.</li>
<li><strong>Example</strong>: Train a linear regression model to identify the relationship between socioeconomic status and test scores.</li>
</ul>
</section>
<section id="ipeds-data-and-supervised-learning" class="level5">
<h5 class="anchored" data-anchor-id="ipeds-data-and-supervised-learning"><strong>2. IPEDS Data and Supervised Learning</strong></h5>
<ul>
<li><strong>Goal</strong>: Develop models to predict institutional enrollment rates based on financial aid, demographics, and program offerings.</li>
<li><strong>Example</strong>: Use logistic regression to forecast whether a student is likely to enroll based on financial aid eligibility.</li>
</ul>
</section>
<section id="oulad-data-and-supervised-learning" class="level5">
<h5 class="anchored" data-anchor-id="oulad-data-and-supervised-learning"><strong>3. OULAD Data and Supervised Learning</strong></h5>
<ul>
<li><strong>Goal</strong>: Predict student outcomes (e.g., pass/fail) based on engagement metrics like forum participation and assignment submissions.</li>
<li><strong>Example</strong>: Train a random forest model to classify students as “at-risk” or “not at-risk” based on weekly interaction data.</li>
</ul>
</section>
</section>
<section id="choosing-the-right-supervised-learning-approach" class="level4">
<h4 class="anchored" data-anchor-id="choosing-the-right-supervised-learning-approach">Choosing the Right Supervised Learning Approach</h4>
<p>When applying supervised learning in Learning Analytics: 1. <strong>Define the Goal</strong>: Clearly articulate the outcome you want to predict (e.g., performance, enrollment, or engagement). 2. <strong>Select an Algorithm</strong>: Choose an appropriate model based on the data and prediction task. - For continuous outcomes, use regression models. - For categorical outcomes, use classification models like logistic regression or random forests. 3. <strong>Feature Engineering</strong>: Select and preprocess relevant features (e.g., attendance, demographics, assignment scores) to improve model accuracy. 4. <strong>Evaluate Model Performance</strong>: Use metrics such as accuracy, precision, recall, or R-squared to assess model effectiveness.</p>
<p>Integrating supervised learning techniques into Learning Analytics, researchers and practitioners can leverage big data to make data-driven predictions and decisions, ultimately enhancing educational outcomes.</p>
</section>
</section>
</section>
<section id="logistic-regression-ml" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-ml">4.3 Logistic Regression ML</h2>
<section id="purpose-case" class="level3">
<h3 class="anchored" data-anchor-id="purpose-case">4.3.1 Purpose + CASE</h3>
<section id="purpose" class="level4">
<h4 class="anchored" data-anchor-id="purpose">Purpose</h4>
<p>Logistic regression is a supervised learning technique widely used for binary classification tasks. It models the probability of an event occurring (e.g., success vs.&nbsp;failure) based on a set of predictor variables. Logistic regression is particularly effective in educational research for predicting outcomes such as retention, enrollment, or graduation rates.</p>
</section>
<section id="case-predicting-graduation-rates" class="level4">
<h4 class="anchored" data-anchor-id="case-predicting-graduation-rates">CASE: Predicting Graduation Rates</h4>
<p>This case study is based on IPEDS data and inspired by Zong and Davis (2022). We predict graduation rates as a binary outcome (<code>good_grad_rate</code>) using institutional features such as total enrollment, admission rate, tuition fees, and average instructional staff salary.</p>
</section>
</section>
<section id="sample-research-questions-rqs" class="level3">
<h3 class="anchored" data-anchor-id="sample-research-questions-rqs">4.3.2 Sample Research Questions (RQs)</h3>
<ul>
<li><strong>RQ A</strong>: What institutional factors are associated with high graduation rates in U.S. four-year universities?</li>
<li><strong>RQ B</strong>: How accurately can we predict high graduation rates using institutional features with supervised machine learning?</li>
</ul>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">4.3.3 Analysis</h3>
<section id="loading-required-packages" class="level4">
<h4 class="anchored" data-anchor-id="loading-required-packages">Loading Required Packages</h4>
<p>We load necessary R packages for data wrangling, cleaning, and modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries for data cleaning, wrangling, and modeling</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co"># For data manipulation and visualization</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels) <span class="co"># For machine learning workflows</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)    <span class="co"># For cleaning variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-and-cleaning-data" class="level4">
<h4 class="anchored" data-anchor-id="loading-and-cleaning-data">Loading and Cleaning Data</h4>
<p>We read the IPEDS dataset and clean column names for easier handling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in IPEDS data from CSV file</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ipeds <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/ipeds-all-title-9-2022-data.csv"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean column names for consistency and usability</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ipeds <span class="ot">&lt;-</span> janitor<span class="sc">::</span><span class="fu">clean_names</span>(ipeds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-wrangling" class="level4">
<h4 class="anchored" data-anchor-id="data-wrangling">Data Wrangling</h4>
<p>Select relevant variables, filter the dataset, and create the dependent variable <code>good_grad_rate</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select and rename key variables; filter relevant institutions</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ipeds <span class="ot">&lt;-</span> ipeds <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> institution_name,                  <span class="co"># Institution name</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_enroll =</span> drvef2022_total_enrollment, <span class="co"># Total enrollment</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_admitted =</span> drvadm2022_percent_admitted_total, <span class="co"># Admission percentage</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">tuition_fees =</span> drvic2022_tuition_and_fees_2021_22, <span class="co"># Tuition fees</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">grad_rate =</span> drvgr2022_graduation_rate_total_cohort, <span class="co"># Graduation rate</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_fin_aid =</span> sfa2122_percent_of_full_time_first_time_undergraduates_awarded_any_financial_aid, <span class="co"># Financial aid</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_salary =</span> drvhr2022_average_salary_equated_to_9_months_of_full_time_instructional_staff_all_ranks <span class="co"># Staff salary</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(grad_rate)) <span class="sc">%&gt;%</span> <span class="co"># Remove rows with missing graduation rates</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create binary dependent variable for high graduation rates</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">good_grad_rate =</span> <span class="fu">if_else</span>(grad_rate <span class="sc">&gt;</span> <span class="dv">62</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">good_grad_rate =</span> <span class="fu">as.factor</span>(good_grad_rate) <span class="co"># Convert to factor</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis-eda" class="level4">
<h4 class="anchored" data-anchor-id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h4>
<p>Visualize the distribution of the graduation rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a histogram of graduation rates</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ipeds <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> grad_rate)) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Graduation Rates"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Graduation Rate"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequency"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter-4_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="logistic-regression-model" class="level4">
<h4 class="anchored" data-anchor-id="logistic-regression-model">Logistic Regression Model</h4>
<p>Fit a logistic regression model to predict high graduation rates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  good_grad_rate <span class="sc">~</span> total_enroll <span class="sc">+</span> pct_admitted <span class="sc">+</span> tuition_fees <span class="sc">+</span> percent_fin_aid <span class="sc">+</span> avg_salary,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> ipeds,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span> <span class="co"># Specify logistic regression for binary outcome</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># View model summary</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = good_grad_rate ~ total_enroll + pct_admitted + 
    tuition_fees + percent_fin_aid + avg_salary, family = "binomial", 
    data = ipeds)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -8.742e-01  6.237e-01  -1.402    0.161    
total_enroll     3.350e-05  7.880e-06   4.251 2.13e-05 ***
pct_admitted    -1.407e-02  3.519e-03  -3.997 6.40e-05 ***
tuition_fees     6.952e-05  4.965e-06  14.003  &lt; 2e-16 ***
percent_fin_aid -2.960e-02  5.652e-03  -5.237 1.64e-07 ***
avg_salary       2.996e-05  3.870e-06   7.740 9.91e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2277  on 1706  degrees of freedom
Residual deviance: 1632  on 1701  degrees of freedom
  (3621 observations deleted due to missingness)
AIC: 1644

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="supervised-ml-workflow" class="level4">
<h4 class="anchored" data-anchor-id="supervised-ml-workflow">Supervised ML Workflow</h4>
<p>Use the <code>tidymodels</code> framework to build a machine learning model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define recipe for the model (preprocessing steps)</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>my_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(good_grad_rate <span class="sc">~</span> total_enroll <span class="sc">+</span> pct_admitted <span class="sc">+</span> tuition_fees <span class="sc">+</span> percent_fin_aid <span class="sc">+</span> avg_salary, <span class="at">data =</span> ipeds)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify logistic regression model with tidymodels</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>my_mod <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">%&gt;%</span>         <span class="co"># Use glm engine for logistic regression</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)    <span class="co"># Specify binary classification task</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create workflow to connect recipe and model</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>my_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(my_rec) <span class="sc">%&gt;%</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(my_mod)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the logistic regression model</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>fit_model <span class="ot">&lt;-</span> <span class="fu">fit</span>(my_wf, ipeds)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate predictions on the dataset</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_model, ipeds) <span class="sc">%&gt;%</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(ipeds) <span class="co"># Combine predictions with original data</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and display accuracy</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>my_accuracy <span class="ot">&lt;-</span> predictions <span class="sc">%&gt;%</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> good_grad_rate, <span class="at">estimate =</span> .pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"accuracy"</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>my_accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.800</code></pre>
</div>
</div>
</section>
</section>
<section id="results-and-discussions" class="level3">
<h3 class="anchored" data-anchor-id="results-and-discussions">4.3.4 Results and Discussions</h3>
<section id="logistic-regression-model-rq-a" class="level4">
<h4 class="anchored" data-anchor-id="logistic-regression-model-rq-a">Logistic Regression Model (RQ A)</h4>
<p>The logistic regression model was fitted to predict whether a university achieves a “good” graduation rate (i.e., graduation rate &gt; 62%) based on several institutional features. The model output is summarized below:</p>
<ul>
<li><strong>Coefficients &amp; Significance</strong>:
<ul>
<li><strong>total_enroll</strong>: Estimate = 3.35e-05, <em>z</em> = 4.251, p = 2.13e-05<br>
<em>Interpretation</em>: As total enrollment increases, the probability of a high graduation rate increases.</li>
<li><strong>pct_admitted</strong>: Estimate = -1.407e-02, <em>z</em> = -3.997, p = 6.40e-05<br>
<em>Interpretation</em>: Higher admission percentages are associated with a lower likelihood of achieving a high graduation rate.</li>
<li><strong>tuition_fees</strong>: Estimate = 6.952e-05, <em>z</em> = 14.003, p &lt; 2e-16<br>
<em>Interpretation</em>: Higher tuition fees are strongly associated with higher graduation rates.</li>
<li><strong>percent_fin_aid</strong>: Estimate = -2.960e-02, <em>z</em> = -5.237, p = 1.64e-07<br>
<em>Interpretation</em>: A higher percentage of students receiving financial aid is associated with a lower probability of a good graduation rate.</li>
<li><strong>avg_salary</strong>: Estimate = 2.996e-05, <em>z</em> = 7.740, p = 9.91e-15<br>
<em>Interpretation</em>: Higher average salaries for instructional staff are positively associated with high graduation rates.</li>
</ul></li>
<li><strong>Model Fit Statistics</strong>:
<ul>
<li><strong>Null Deviance</strong>: 2277 (on 1706 degrees of freedom)</li>
<li><strong>Residual Deviance</strong>: 1632 (on 1701 degrees of freedom)</li>
<li><strong>AIC</strong>: 1644</li>
<li>Note: 3621 observations were deleted due to missing values.</li>
</ul></li>
</ul>
<p>Overall, the regression model demonstrates that several institutional factors are statistically significant predictors of graduation rates. In particular, tuition fees and avg_salary have a strong positive effect, while pct_admitted and percent_fin_aid show negative associations.</p>
</section>
<section id="supervised-ml-workflow-results-rq-b" class="level4">
<h4 class="anchored" data-anchor-id="supervised-ml-workflow-results-rq-b">Supervised ML Workflow Results (RQ B)</h4>
<p>Using the tidymodels framework, we built a logistic regression model as part of a supervised machine learning workflow. The performance metric obtained is as follows:</p>
<ul>
<li><strong>Accuracy</strong>: 80.02%</li>
</ul>
<p>This indicates that the machine learning model correctly classified approximately 80% of the institutions as having either a good or not good graduation rate, based on the selected predictors.</p>
</section>
<section id="overall-discussion" class="level4">
<h4 class="anchored" data-anchor-id="overall-discussion">Overall Discussion</h4>
<ul>
<li><strong>Similarities between Approaches</strong>:
<ul>
<li>Both the traditional logistic regression and the tidymodels workflow identified key predictors that influence graduation rates, such as total enrollment, admission percentage, tuition fees, financial aid percentage, and average staff salary.</li>
<li>Each approach provides valuable insights: the regression model offers detailed coefficient estimates and significance levels, while the tidymodels workflow emphasizes predictive accuracy.</li>
</ul></li>
<li><strong>Differences between Approaches</strong>:
<ul>
<li><strong>Interpretability vs.&nbsp;Predictive Performance</strong>: The logistic regression output delivers interpretability through its coefficients and p-values, allowing us to understand the direction and magnitude of the relationships. In contrast, the supervised ML workflow focuses on achieving a robust predictive performance, evidenced by an 80% accuracy.</li>
<li><strong>Handling of Data</strong>: The traditional regression model summarizes the relationship between variables, whereas the ML workflow integrates data pre-processing, modeling, and validation into a cohesive framework.</li>
</ul></li>
</ul>
<p>In summary, our analyses indicate that institutional factors, particularly tuition fees and staff salaries, play a significant role in predicting graduation outcomes. The supervised ML approach, with an accuracy of around 80%, confirms the model’s practical utility in classifying institutions based on graduation performance. Both methods complement each other, providing a comprehensive understanding of the underlying dynamics that drive graduation rates in higher education.</p>
</section>
</section>
</section>
<section id="random-forests-ml-on-interactions-data" class="level2">
<h2 class="anchored" data-anchor-id="random-forests-ml-on-interactions-data">4.4 Random Forests ML on Interactions Data</h2>
<p>In this section, we explore a more sophisticated supervised learning approach—Random Forests—to model student interactions data from the Open University Learning Analytics Dataset (OULAD). Building on our earlier work with logistic regression and evaluation metrics, this case study examines whether a random forest model can improve predictive performance when leveraging clickstream data from the virtual learning environment (VLE).</p>
<section id="purpose-case-1" class="level3">
<h3 class="anchored" data-anchor-id="purpose-case-1">4.4.1 Purpose + CASE</h3>
<section id="purpose-1" class="level4">
<h4 class="anchored" data-anchor-id="purpose-1">Purpose</h4>
<p>Random Forests is an ensemble learning method that builds multiple decision trees and aggregates their results to improve prediction accuracy and control over-fitting. It is particularly well suited for complex, high-dimensional data such as student interaction (clickstream) data. This approach not only provides robust predictions but also offers insights into variable importance, helping us understand which features most influence student outcomes.</p>
</section>
<section id="case" class="level4">
<h4 class="anchored" data-anchor-id="case">CASE</h4>
<p>Inspired by research on digital trace data (e.g., Rodriguez et al., 2021; Bosch, 2021), this case study uses pre-processed interactions data from OULAD. In our analysis, we focus on predicting whether a student will pass the course (a binary outcome) based on engineered features derived from clickstream data. These features include the total number of clicks (<code>sum_clicks</code>), summary statistics (mean and standard deviation of clicks), and linear trends over time (slope and intercept from clickstream patterns).</p>
</section>
</section>
<section id="sample-research-questions" class="level3">
<h3 class="anchored" data-anchor-id="sample-research-questions">4.4.2 Sample Research Questions</h3>
<ul>
<li><strong>RQ1:</strong> How accurately can a random forest model predict whether a student will pass a course using interactions data from OULAD?</li>
<li><strong>RQ2:</strong> Which interaction-based features (e.g., total clicks, click stream slope) are most important in predicting student outcomes?</li>
<li><strong>RQ3:</strong> How does the use of cross-validation (e.g., v-fold CV) influence the stability and generalizability of the random forest model on interactions data?</li>
</ul>
</section>
<section id="analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="analysis-1">4.4.3 Analysis</h3>
<section id="loading-required-packages-1" class="level4">
<h4 class="anchored" data-anchor-id="loading-required-packages-1">Loading Required Packages</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries for data manipulation and modeling</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)      <span class="co"># Data wrangling and visualization</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)        <span class="co"># Cleaning variable names</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)     <span class="co"># Modeling workflow</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)         <span class="co"># Random forest implementation</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)            <span class="co"># Variable importance plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-and-preparing-the-data" class="level4">
<h4 class="anchored" data-anchor-id="loading-and-preparing-the-data">Loading and Preparing the Data</h4>
<p>We load the pre-filtered interactions data from OULAD along with a students-and-assessments file, then join them to create a complete dataset for modeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the interactions data (filtered for the first one-third of the semester)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>interactions <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/oulad-interactions-filtered.csv"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the students and assessments data</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>students_and_assessments <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/oulad-students-and-assessments.csv"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cut-off dates based on assessments data (using first quantile as intervention point)</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>assessments <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/oulad-assessments.csv"</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cut-off dates based on assessments data using the correct date column 'date_submitted'</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>code_module_dates <span class="ot">&lt;-</span> assessments <span class="sc">%&gt;%</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(code_module, code_presentation) <span class="sc">%&gt;%</span> </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">quantile_cutoff_date =</span> <span class="fu">quantile</span>(date_submitted, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Join interactions with the cutoff dates and filter</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>interactions_joined <span class="ot">&lt;-</span> interactions <span class="sc">%&gt;%</span> </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(code_module_dates, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"code_module"</span>, <span class="st">"code_presentation"</span>))</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>interactions_joined <span class="ot">&lt;-</span> interactions_joined <span class="sc">%&gt;%</span> </span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>quantile_cutoff_date.x) <span class="sc">%&gt;%</span> </span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">quantile_cutoff_date =</span> quantile_cutoff_date.y)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter interactions to include only those before the cutoff date</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>interactions_filtered <span class="ot">&lt;-</span> interactions_joined <span class="sc">%&gt;%</span> </span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(date <span class="sc">&lt;</span> quantile_cutoff_date)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize interactions: total clicks, mean and standard deviation</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>interactions_summarized <span class="ot">&lt;-</span> interactions_filtered <span class="sc">%&gt;%</span> </span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(id_student, code_module, code_presentation) <span class="sc">%&gt;%</span> </span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>      <span class="at">sum_clicks =</span> <span class="fu">sum</span>(sum_click),</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd_clicks =</span> <span class="fu">sd</span>(sum_click), </span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean_clicks =</span> <span class="fu">mean</span>(sum_click)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a><span class="co"># (Optional) Further feature engineering: derive linear slopes from clickstream</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>fit_model <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tryCatch</span>(</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>        { </span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>            model <span class="ot">&lt;-</span> <span class="fu">lm</span>(sum_click <span class="sc">~</span> date, <span class="at">data =</span> data)</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>            <span class="fu">tidy</span>(model)</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>        },</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>        <span class="at">error =</span> <span class="cf">function</span>(e) { <span class="fu">tibble</span>(<span class="at">term =</span> <span class="cn">NA</span>, <span class="at">estimate =</span> <span class="cn">NA</span>, <span class="at">std.error =</span> <span class="cn">NA</span>, <span class="at">statistic =</span> <span class="cn">NA</span>, <span class="at">p.value =</span> <span class="cn">NA</span>) },</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>        <span class="at">warning =</span> <span class="cf">function</span>(w) { <span class="fu">tibble</span>(<span class="at">term =</span> <span class="cn">NA</span>, <span class="at">estimate =</span> <span class="cn">NA</span>, <span class="at">std.error =</span> <span class="cn">NA</span>, <span class="at">statistic =</span> <span class="cn">NA</span>, <span class="at">p.value =</span> <span class="cn">NA</span>) }</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>interactions_slopes <span class="ot">&lt;-</span> interactions_filtered <span class="sc">%&gt;%</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(id_student, code_module, code_presentation) <span class="sc">%&gt;%</span></span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>    <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">model =</span> <span class="fu">map</span>(data, fit_model)) <span class="sc">%&gt;%</span></span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unnest</span>(model) <span class="sc">%&gt;%</span></span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(code_module, code_presentation, id_student, term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(term)) <span class="sc">%&gt;%</span></span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> term, <span class="at">values_from =</span> estimate) <span class="sc">%&gt;%</span></span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">intercept =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, <span class="at">slope =</span> date)</span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Join summarized clicks and slopes features</span></span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a>interactions_features <span class="ot">&lt;-</span> <span class="fu">left_join</span>(interactions_summarized, interactions_slopes, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"id_student"</span>, <span class="st">"code_module"</span>, <span class="st">"code_presentation"</span>))</span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Finally, join with students_and_assessments to get the outcome variable</span></span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a>students_assessments_and_interactions <span class="ot">&lt;-</span> <span class="fu">left_join</span>(students_and_assessments, interactions_features, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"id_student"</span>, <span class="st">"code_module"</span>, <span class="st">"code_presentation"</span>))</span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure outcome variable 'pass' is a factor</span></span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a>students_assessments_and_interactions <span class="ot">&lt;-</span> students_assessments_and_interactions <span class="sc">%&gt;%</span> </span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">pass =</span> <span class="fu">as.factor</span>(pass))</span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Inspect the final dataset</span></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a>students_assessments_and_interactions <span class="sc">%&gt;%</span> </span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a>    skimr<span class="sc">::</span><span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">32593</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">code_module</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">code_presentation</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gender</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">region</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">highest_education</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">age_band</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">disability</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">final_result</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pass</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">0: 20232, 1: 12361</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id_student</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">706687.67</td>
<td style="text-align: right;">549167.31</td>
<td style="text-align: right;">3733.00</td>
<td style="text-align: right;">508573.00</td>
<td style="text-align: right;">590310.00</td>
<td style="text-align: right;">644453.00</td>
<td style="text-align: right;">2716795.00</td>
<td style="text-align: left;">▅▇▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">imd_band</td>
<td style="text-align: right;">4627</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">5.62</td>
<td style="text-align: right;">2.73</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: left;">▃▇▇▆▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">num_of_prev_attempts</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">studied_credits</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">79.76</td>
<td style="text-align: right;">41.07</td>
<td style="text-align: right;">30.00</td>
<td style="text-align: right;">60.00</td>
<td style="text-align: right;">60.00</td>
<td style="text-align: right;">120.00</td>
<td style="text-align: right;">655.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">module_presentation_length</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">256.01</td>
<td style="text-align: right;">13.18</td>
<td style="text-align: right;">234.00</td>
<td style="text-align: right;">241.00</td>
<td style="text-align: right;">262.00</td>
<td style="text-align: right;">268.00</td>
<td style="text-align: right;">269.00</td>
<td style="text-align: left;">▇▁▁▅▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">date_registration</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">-69.41</td>
<td style="text-align: right;">49.26</td>
<td style="text-align: right;">-322.00</td>
<td style="text-align: right;">-100.00</td>
<td style="text-align: right;">-57.00</td>
<td style="text-align: right;">-29.00</td>
<td style="text-align: right;">167.00</td>
<td style="text-align: left;">▁▂▇▃▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">date_unregistration</td>
<td style="text-align: right;">22521</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">49.76</td>
<td style="text-align: right;">82.46</td>
<td style="text-align: right;">-365.00</td>
<td style="text-align: right;">-2.00</td>
<td style="text-align: right;">27.00</td>
<td style="text-align: right;">109.00</td>
<td style="text-align: right;">444.00</td>
<td style="text-align: left;">▁▁▇▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">mean_weighted_score</td>
<td style="text-align: right;">7958</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">544.70</td>
<td style="text-align: right;">381.39</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">160.00</td>
<td style="text-align: right;">610.00</td>
<td style="text-align: right;">875.00</td>
<td style="text-align: right;">1512.00</td>
<td style="text-align: left;">▇▃▇▅▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sum_clicks</td>
<td style="text-align: right;">3495</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">474.93</td>
<td style="text-align: right;">572.89</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">128.00</td>
<td style="text-align: right;">295.50</td>
<td style="text-align: right;">604.00</td>
<td style="text-align: right;">10712.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd_clicks</td>
<td style="text-align: right;">3753</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">5.51</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.37</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: right;">6.44</td>
<td style="text-align: right;">560.24</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mean_clicks</td>
<td style="text-align: right;">3495</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">3.19</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.33</td>
<td style="text-align: right;">2.95</td>
<td style="text-align: right;">3.82</td>
<td style="text-align: right;">47.12</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">3640</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: right;">-585.59</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: right;">3.66</td>
<td style="text-align: right;">130.83</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">slope</td>
<td style="text-align: right;">4441</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">-12.17</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">20.12</td>
<td style="text-align: left;">▁▇▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="creating-the-model-recipe" class="level4">
<h4 class="anchored" data-anchor-id="creating-the-model-recipe">Creating the Model Recipe</h4>
<p>We build a recipe that includes the engineered features from interactions data along with other predictors from the students data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>my_rec2 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(pass <span class="sc">~</span> disability <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                     date_registration <span class="sc">+</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                     gender <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                     code_module <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                     mean_weighted_score <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                     sum_clicks <span class="sc">+</span> sd_clicks <span class="sc">+</span> mean_clicks <span class="sc">+</span> </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                     intercept <span class="sc">+</span> slope, </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> students_assessments_and_interactions) <span class="sc">%&gt;%</span> </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(disability) <span class="sc">%&gt;%</span> </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(gender) <span class="sc">%&gt;%</span>  </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(code_module) <span class="sc">%&gt;%</span> </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(mean_weighted_score) <span class="sc">%&gt;%</span> </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(sum_clicks) <span class="sc">%&gt;%</span> </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(sd_clicks) <span class="sc">%&gt;%</span> </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(mean_clicks) <span class="sc">%&gt;%</span> </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(intercept) <span class="sc">%&gt;%</span> </span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(slope) <span class="sc">%&gt;%</span> </span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_impute_knn</span>(date_registration) <span class="sc">%&gt;%</span> </span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="specifying-the-model-and-workflow" class="level4">
<h4 class="anchored" data-anchor-id="specifying-the-model-and-workflow">Specifying the Model and Workflow</h4>
<p>We use a random forest model via the <code>ranger</code> engine and set up our workflow.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify random forest model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>my_mod2 <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create workflow to bundle the recipe and model</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>my_wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_recipe</span>(my_rec2) <span class="sc">%&gt;%</span> </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(my_mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="resampling-and-model-fitting" class="level4">
<h4 class="anchored" data-anchor-id="resampling-and-model-fitting">Resampling and Model Fitting</h4>
<p>We perform cross-validation (v-fold CV) to estimate model performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 4-fold cross-validation on training data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>vfcv <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(<span class="at">data =</span> students_assessments_and_interactions, <span class="at">v =</span> <span class="dv">4</span>, <span class="at">strata =</span> pass)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify metrics: accuracy, sensitivity, specificity, ppv, npv, and Cohen's kappa</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>class_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(accuracy, sensitivity, specificity, ppv, npv, kap)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model using resampling</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>fitted_model_resamples <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(my_wf2, <span class="at">resamples =</span> vfcv, <span class="at">metrics =</span> class_metrics)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Collect and display metrics</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(fitted_model_resamples)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  .metric     .estimator  mean     n  std_err .config             
  &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;               
1 accuracy    binary     0.671     4 0.00165  Preprocessor1_Model1
2 kap         binary     0.264     4 0.00340  Preprocessor1_Model1
3 npv         binary     0.590     4 0.00327  Preprocessor1_Model1
4 ppv         binary     0.703     4 0.000926 Preprocessor1_Model1
5 sensitivity binary     0.815     4 0.00209  Preprocessor1_Model1
6 specificity binary     0.436     4 0.00145  Preprocessor1_Model1</code></pre>
</div>
</div>
</section>
<section id="final-model-fit-and-evaluation" class="level4">
<h4 class="anchored" data-anchor-id="final-model-fit-and-evaluation">Final Model Fit and Evaluation</h4>
<p>Finally, we fit the model on the full training set (using last_fit) and evaluate its predictions on the test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split data into training and testing sets (e.g., 33% for testing)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20230712</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>train_test_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(students_assessments_and_interactions, <span class="at">prop =</span> <span class="fl">0.67</span>, <span class="at">strata =</span> pass)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>data_train <span class="ot">&lt;-</span> <span class="fu">training</span>(train_test_split)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(train_test_split)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit final model on the training set and evaluate on the test set</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>final_fit <span class="ot">&lt;-</span> <span class="fu">last_fit</span>(my_wf2, train_test_split, <span class="at">metrics =</span> class_metrics)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Collect and display final metrics</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(final_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  .metric     .estimator .estimate .config             
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
1 accuracy    binary         0.665 Preprocessor1_Model1
2 sensitivity binary         0.815 Preprocessor1_Model1
3 specificity binary         0.419 Preprocessor1_Model1
4 ppv         binary         0.697 Preprocessor1_Model1
5 npv         binary         0.580 Preprocessor1_Model1
6 kap         binary         0.247 Preprocessor1_Model1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate and display a confusion matrix for final predictions</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_predictions</span>(final_fit) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">conf_mat</span>(.pred_class, pass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction    0    1
         0 5439 1238
         1 2370 1710</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the fitted model from the final workflow and plot variable importance</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>final_fit <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pluck</span>(<span class="st">".workflow"</span>, <span class="dv">1</span>) <span class="sc">%&gt;%</span>   <span class="co"># Extract the workflow object from the final fit</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span>   <span class="co"># Retrieve the fitted model from the workflow</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>(<span class="at">num_features =</span> <span class="dv">10</span>)      <span class="co"># Plot the top 10 important features</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter-4_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the fitted model from the workflow</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>final_model <span class="ot">&lt;-</span> final_fit <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pluck</span>(<span class="st">".workflow"</span>, <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>()</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the variable importance values from the fitted model</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>importance_values <span class="ot">&lt;-</span> final_model<span class="sc">$</span>fit<span class="sc">$</span>variable.importance</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the variable importance values</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(importance_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  date_registration mean_weighted_score          sum_clicks           sd_clicks 
          652.14806           838.06052          1062.49141           778.63848 
        mean_clicks           intercept               slope        disability_Y 
          737.79417           729.52344           739.85682            60.93367 
           gender_M     code_module_BBB     code_module_CCC     code_module_DDD 
           79.62440            77.18477            70.72006            46.68243 
    code_module_EEE     code_module_FFF     code_module_GGG 
           28.26595            74.31310            35.27026 </code></pre>
</div>
</div>
</section>
</section>
<section id="results-and-discussions-1" class="level3">
<h3 class="anchored" data-anchor-id="results-and-discussions-1">4.4.4 Results and Discussions</h3>
<section id="research-question-1-rq1" class="level4">
<h4 class="anchored" data-anchor-id="research-question-1-rq1">Research Question 1 (RQ1):</h4>
<p><em>How accurately can a random forest model predict whether a student will pass a course using interactions data from OULAD?</em></p>
<p><strong>Response:</strong><br>
Using 4-fold cross-validation, our random forest model yielded an average accuracy of approximately <strong>67.0%</strong> (mean accuracy from resamples: 0.670) with a Cohen’s Kappa of <strong>0.261</strong>, suggesting moderate agreement beyond chance. When fitted on the entire training set and evaluated on the test set, the final model showed an accuracy of <strong>66.5%</strong> along with: - <strong>Sensitivity:</strong> 81.5% – indicating the model correctly identifies a high proportion of students who pass. - <strong>Specificity:</strong> 41.9% – suggesting that the model is less effective at correctly identifying students who do not pass. - <strong>Positive Predictive Value (PPV):</strong> 69.7% - <strong>Negative Predictive Value (NPV):</strong> 58.0%</p>
<p>The confusion matrix shows: - True Negatives (TN): 5439 - False Negatives (FN): 1238 - False Positives (FP): 2370 - True Positives (TP): 1710</p>
<p>Overall, these metrics indicate that while the model performs well in detecting positive outcomes (high sensitivity), its lower specificity means that it tends to misclassify a relatively higher proportion of non-passing students.</p>
</section>
<section id="research-question-2-rq2" class="level4">
<h4 class="anchored" data-anchor-id="research-question-2-rq2">Research Question 2 (RQ2):</h4>
<p><em>Which interaction-based features are most important in predicting student outcomes?</em></p>
<p><strong>Response:</strong><br>
The variable importance analysis, extracted from the final random forest model using the <code>vip()</code> function, highlights the following key predictors (with their respective importance scores):</p>
<ul>
<li><strong>sum_clicks:</strong> 1062.49 – This is the most influential feature, indicating that the total number of clicks (i.e., student engagement) in the VLE is a strong predictor of student success.</li>
<li><strong>mean_weighted_score:</strong> 838.06 – Reflecting academic performance as measured by weighted assessment scores.</li>
<li><strong>mean_clicks:</strong> 737.79, <strong>slope:</strong> 739.86, and <strong>intercept:</strong> 729.52 – These engineered features representing the central tendency and trend of click behavior further underline the importance of digital engagement patterns.</li>
<li><strong>date_registration:</strong> 652.15 – The registration date also plays a significant role.</li>
<li>Other categorical variables (e.g., dummy-coded <code>disability</code>, <code>gender</code>, and <code>code_module</code> levels) generally show lower importance scores, with values typically under 80, indicating that while they do contribute, engagement and performance metrics dominate.</li>
</ul>
<p>These results suggest that both the intensity and the temporal trend of student interactions with the learning environment are critical in predicting whether a student will pass.</p>
</section>
<section id="research-question-3-rq3" class="level4">
<h4 class="anchored" data-anchor-id="research-question-3-rq3">Research Question 3 (RQ3):</h4>
<p><em>How does the use of cross-validation impact the stability and generalizability of the random forest model on interactions data?</em></p>
<p><strong>Response:</strong><br>
The use of 4-fold cross-validation (via <code>vfold_cv</code>) allowed us to assess the model’s performance across multiple subsets of the data, mitigating the risk of overfitting. The resampling results are relatively consistent (with accuracy around 67%, sensitivity at 81.6%, and specificity around 43.2%), which supports the model’s robustness and generalizability. Although the final test set performance (accuracy of 66.5%) is slightly lower, the overall consistency of metrics across folds indicates that our model is stable when applied to unseen data.</p>
</section>
<section id="overall-discussion-1" class="level4">
<h4 class="anchored" data-anchor-id="overall-discussion-1">Overall Discussion</h4>
<p>The random forest model built on interactions data from OULAD demonstrates decent predictive performance with an accuracy of approximately 66.5–67% and high sensitivity (around 81.5%), indicating strong capability in identifying students who will pass the course. However, the relatively low specificity (around 42%) suggests that there is room for improvement in correctly classifying students who are at risk of not passing.</p>
<p>The variable importance analysis underscores that engagement-related features—especially <strong>sum_clicks</strong> and features capturing the trend in interactions (slope, mean_clicks)—are the most influential predictors. This insight implies that the digital footprint of student engagement in the virtual learning environment is critical for predicting academic outcomes.</p>
<p>In summary, while our model performs robustly across cross-validation folds and provides actionable insights into key predictive features, the lower specificity points to the need for further refinement. Future work might explore additional feature engineering, alternative model tuning, or combining models to better balance sensitivity and specificity, ultimately supporting timely interventions in educational settings.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter-3.html" class="pagination-link" aria-label="Networks Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Networks Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./section-3-intro.html" class="pagination-link" aria-label="LLMs Methods">
        <span class="nav-page-text">LLMs Methods</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>